#!/usr/bin/env bash
# Shows "Holberton School", "Bad luck", "Good luck"
i=0
while [ $i -lt 10 ];
do
    if [ $i -eq 3 ]; then
        echo "bad luck"
    elif [ $i -eq 7 ]; then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i++))
done