#!/usr/bin/env bash
# Process and PID file
echo $$ > /var/run/myscript.pid

trap "echo I hate the kill command; exit_f" 15
trap "Y U no love me?!" 2
trap "exit_f" 3

exit_f()
{
    rm /var/run/holbertonscript.pid
    exit
}

while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done