#!/usr/bin/env bash
# Manages manage_my_process

DAEMON_PID_FILE="/var/run/my_process.pid"
case "$1" in
    start)
	./manage_my_process &
	echo $! > $DAEMON_PID_FILE
	echo "manage_my_process started"
	;;
    stop)
	kill "$(cat $DAEMON_PID_FILE)"
	rm $DAEMON_PID_FILE
	echo "manage_my_process stopped"
	;;
    restart)
	kill "$(cat $DAEMON_PID_FILE)"
	rm $DAEMON_PID_FILE
	./manage_my_process &
	echo $! > $DAEMON_PID_FILE
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
esac